config/routes.rb
Rails.application.routes.draw do
  resources :work_orders
  scope '/dashboard' do
      resources :parts, :vendors, :policies, :roles, :part_orders
      get 'part/search', to: 'parts#search'
      get 'vendor/search', to: 'vendors#search'
      get 'role/search', to: 'roles#search'
      get 'policy/search', to: 'policies#search'
      get 'part_order/search', to: 'part_orders#search'
      get 'part_order/search_vendor', to: 'part_orders#search_vendor'
      get 'part_order/search_name', to: 'part_orders#search_name'
  end
  get 'dashboard_unauth/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "dashboard#index"

  get 'dashboard/users', to: 'users#index'
  put 'dashboard/users/:id', to: 'users#update_role', as: :user_update_roles

  get 'dashboard_unauth/orders', to: 'dashboard_unauth#orders'
  get 'dashboard_unauth/products', to: 'dashboard_unauth#products'
  get 'dashboard_unauth/customers', to: 'dashboard_unauth#customers'
  get 'dashboard_unauth/users', to: 'dashboard_unauth#users'
  get 'dashboard_unauth/departments', to: 'dashboard_unauth#departments'



end

app/models/part_order.rb
class PartOrder < ApplicationRecord
end

app/controllers/part_orders_controller.rb
class PartOrdersController < ApplicationController
  before_action :set_part_order, only: %i[ show edit update destroy ]
  layout 'dashboard'

  # GET /part_orders or /part_orders.json
  def index
    @part_orders = PartOrder.all
  end

  def search
    q = params[:q].downcase
    @parts = Part.where("mfr_number LIKE ?", "%#{q}%").limit(5)
  end

  def search_name
    q = params[:q].downcase
    @parts = Part.where("name LIKE ?", "%#{q}%").limit(5)
  end

  def search_vendor
    q = params[:q].downcase
    @vendors = Vendor.where("name LIKE ?", "%#{q}%").limit(5)
  end

  # GET /part_orders/1 or /part_orders/1.json
  def show
  end

  # GET /part_orders/new
  def new
    @part_order = PartOrder.new
  end

  # GET /part_orders/1/edit
  def edit
  end

  # POST /part_orders or /part_orders.json
  def create
    @part_order = PartOrder.new(part_order_params)

    respond_to do |format|
      if @part_order.save
        format.html { redirect_to @part_order, notice: "Part order was successfully created." }
        format.json { render :show, status: :created, location: @part_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @part_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /part_orders/1 or /part_orders/1.json
  def update
    respond_to do |format|
      if @part_order.update(part_order_params)
        format.html { redirect_to @part_order, notice: "Part order was successfully updated." }
        format.json { render :show, status: :ok, location: @part_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @part_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /part_orders/1 or /part_orders/1.json
  def destroy
    @part_order.destroy
    respond_to do |format|
      format.html { redirect_to part_orders_url, notice: "Part order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part_order
      @part_order = PartOrder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def part_order_params
      params.require(:part_order).permit(:part_name, :part_description, :vendor_id, :po_number, :vendor, :vendor_contact, :vendor_address, :quantity, :total)
    end
end

app/helpers/part_orders_helper.rb
module PartOrdersHelper
end

app/views/part_orders/_form.html.erb
<style>
  .card-container {
    margin-top: 20px;
  }

  .card-header {

    background-color: blue;
    color: white;
  }
</style>
<div class="card-container">
  
  <div class="card">
  <div class="card-header">
    Parts
  </div>
  <div class="card-body">
     <div class="form-group row">

    <label for="championPart" class="col-sm-2 col-form-label">Champion Part #</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" id="championPart">
    </div>
    <label for="partDescription" class="col-sm-2 col-form-label">Part Description</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" id="partDescription">
    </div>
  </div>
  <div class="form-group row">
    <label for="championPart" class="col-sm-2 col-form-label">OEM Part #</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" id="championPart">
    </div>
  </div>
  <div class="form-group row">
    <label for="championPart" class="col-sm-2 col-form-label">MFG Part #</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" id="championPart">
    </div>
  </div>

  <br>

  <h5>Order Information</h5>
  <div class="form-group row">

    <label for="Order" class="col-sm-2 col-form-label">Order Quantity</label>
    <div class="col-sm-2">
      <input type="text" class="form-control" id="Order">
    </div>
    <label for="Delivery" class="col-sm-2 col-form-label">Delivery Date</label>
    <div class="col-sm-2">
      <input type="text" class="form-control" id="Delivery">
    </div>
    <label for="poNumber" class="col-sm-2 col-form-label">PO Number</label>
    <div class="col-sm-2">
      <input type="text" class="form-control" id="poNumber">
    </div>
  </div>

   <br>

  <h5>Vendor Information</h5>
   <div class="form-group row">

    <label for="SelectVendor" class="col-sm-2 col-form-label">Select Vendor</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" id="SelectVendor">
    </div>
  </div>
  <div class="form-group row">
    <label for="VendorName" class="col-sm-2 col-form-label">Vendor Name</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" id="VendorName">
    </div>
  </div>
  <div class="form-group row">
    <label for="VendorPhoneNumber" class="col-sm-2 col-form-label">Vendor Phone Number</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" id="VendorPhoneNumber">
    </div>
  </div>
  <div class="form-group row">
    <label for="VendorEmail" class="col-sm-2 col-form-label">Vendor Email</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" id="VendorEmail">
    </div>
  </div>
  <div class="form-group row">
    <label for="VendorAddress" class="col-sm-2 col-form-label">Vendor Address</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" id="VendorAddress">
    </div>
  </div>


<br>
  <a href="#" class="btn btn-primary">Save and Close</a>
    <a href="#" class="btn btn-primary" style="float: right;">Cancel</a>
  </div>
</div>

</div>

<%= form_with(model: part_order) do |form| %>
  <% if part_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(part_order.errors.count, "error") %> prohibited this part_order from being saved:</h2>

      <ul>
        <% part_order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="col-md-6">
    <div class="form-group">
      <%= form.label :part_name %>
      <%= form.text_field :part_name, data: {behavior: "autocomplete-parts-name"}, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :part_mhr_number %>
      <%= form.text_field :mhr_number, data: {behavior: "autocomplete-parts-mhrnumber"}, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :part_description %>
      <%= form.text_area :part_description, class: "form-control" %>
    </div>

     <div class="form-group">
      <%= form.label :vendor_id %>
      <%= form.text_field :vendor_id,  class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= form.label :vendor_name %>
      <%= form.text_field :vendor, data: {behavior: "autocomplete-order-vendors"}, class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= form.label :vendor_contact_person %>
      <%= form.text_field :vendor_contact, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :vendor_address %>
      <%= form.text_field :vendor_address, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :quantity %>
      <%= form.number_field :quantity, class: "form-control" %>
    </div>

     <div class="form-group">
      <%= form.label :total %>
      <%= form.number_field :total, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :po_number %>
      <%= form.text_field :po_number,  class: "form-control"  %>
    </div>


    <div class="form-group">
      <%= form.submit "Submit", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>
</div>

app/views/part_orders/edit.html.erb
<h1>Editing Part Order</h1>

<%= render 'form', part_order: @part_order %>

<%= link_to 'Show', @part_order %> |
<%= link_to 'Back', part_orders_path %>

app/views/part_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Part Orders</h1>

<table>
  <thead>
    <tr>
      <th>Part name</th>
      <th>Part description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @part_orders.each do |part_order| %>
      <tr>
        <td><%= part_order.part_name %></td>
        <td><%= part_order.part_description %></td>
        <td><%= link_to 'Show', part_order %></td>
        <td><%= link_to 'Edit', edit_part_order_path(part_order) %></td>
        <td><%= link_to 'Destroy', part_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Part Order', new_part_order_path %>

app/views/part_orders/new.html.erb
<h1>New Part Order</h1>

<%= render 'form', part_order: @part_order %>

<%= link_to 'Back', part_orders_path %>

app/views/part_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Part name:</strong>
  <%= @part_order.part_name %>
</p>

<p>
  <strong>Part description:</strong>
  <%= @part_order.part_description %>
</p>

<%= link_to 'Edit', edit_part_order_path(@part_order) %> |
<%= link_to 'Back', part_orders_path %>